### ISSUE TITLE
RuntimeError: mat1 dim 1 must match mat2 dim 0

### ISSUE THREAD

**Issue by MENGM0** [zsyasd/Excavating-RoI-Attention-for-Underwater-Object-Detection#2]
when i run train.py in several epochs(fig.1), the program is stopped due to "**RuntimeError: mat1 dim 1 must match mat2 dim 0**" (fig.2) in tr_head.py class ExternalAttention(fig.3).
![image](https://user-images.githubusercontent.com/44924137/197699203-b7e46ecf-eda7-4ce1-a5e3-ec7745f47ad0.png)

![image](https://user-images.githubusercontent.com/44924137/197699029-cc671e47-29e0-4780-9bbc-d54375f89e95.png)

![image](https://user-images.githubusercontent.com/44924137/197699440-ad5badbf-748e-4f8e-841f-80da0b61457a.png)

**Comment by zsyasd** [comment]
我看到你主页有用中文···我直接用中文跟你讲了··看的大家都舒服一点。
你改过代码吗？或者你这个数据集是什么数据集啊？你换成voc或者utdac跑过吗。
因为你这个确实很神奇··已经把所有图片遍历了一轮了还出现这个报错···

**Comment by MENGM0** [comment]
感谢您的回复！
我用自己的数据集，coco格式，所有图片分辨率一致，我是新建文件复制您的配置文件，跑通了。
我也很奇怪跑同了还有这种错误。我重复了三次，有第2个、第4个epoch报错的，有点迷。

**Comment by MENGM0** [comment]
明天我试下voc格式。

**Comment by zsyasd** [comment]
确实很奇怪···一般来说如果是第一个epoch没跑完就出现这种错误有可能是图片有问题。但是跑完一轮了还出现这种错误确实很迷····
你可以试一试换Linux机器跑一跑，有时候win确实也会出现一些奇奇怪怪的bug··

**Comment by MENGM0** [comment]
非常感谢您的工作！我使用您的仓库跑通了并且在我的数据集效果很好，我猜测是mmdet的版本问题。

**Comment by Allmightwow** [comment]
我也出现了这个错误，请问你是怎么解决的..

**Comment by meixiangzhang** [comment]
请问你们解决了吗？我运行了多次，每次出现的错误还不一样，跑着跑着就出错了，没有训练完1个epoch。但刚开始几百张图像训练是没有报错的。

` --------------------
2023-08-17 11:45:27,708 - mmdet - INFO - workflow: [('train', 1)], max: 12 epochs
2023-08-17 11:45:27,708 - mmdet - INFO - Checkpoints will be saved to F:\2\underwater\Excavating-RoI-Attention-for-Underwater-Object-Detection-main\work
_dirs\roitransformer_r50_fpn_1x_coco by HardDiskBackend.
2023-08-17 11:46:09,101 - mmdet - INFO - Epoch [1][50/2853]     lr: 4.945e-04, eta: 7:46:31, time: 0.819, data_time: 0.125, memory: 12167, loss_rpn_cls:
 0.6923, loss_rpn_bbox: 0.0235, loss_cls: 0.8327, acc: 86.4277, loss_bbox: 0.0526, loss: 1.6011
2023-08-17 11:46:42,417 - mmdet - INFO - Epoch [1][100/2853]    lr: 9.940e-04, eta: 7:02:25, time: 0.666, data_time: 0.012, memory: 12167, loss_rpn_cls:
 0.6868, loss_rpn_bbox: 0.0208, loss_cls: 0.1771, acc: 98.2598, loss_bbox: 0.0149, loss: 0.8995
2023-08-17 11:47:16,633 - mmdet - INFO - Epoch [1][150/2853]    lr: 1.494e-03, eta: 6:50:46, time: 0.684, data_time: 0.018, memory: 12167, loss_rpn_cls:
 0.6753, loss_rpn_bbox: 0.0219, loss_cls: 0.2636, acc: 97.1875, loss_bbox: 0.0665, loss: 1.0273
Traceback (most recent call last):
  File "tools/train.py", line 196, in <module>
    main()
  File "tools/train.py", line 192, in main
    meta=meta)
  File "f:\2\underwater\excavating-roi-attention-for-underwater-object-detection-main\mmdet\apis\train.py", line 209, in train_detector
    runner.run(data_loaders, cfg.workflow)
  File "h:\mmcv-1.4.6\mmcv\runner\epoch_based_runner.py", line 127, in run
    epoch_runner(data_loaders[i], **kwargs)
  File "h:\mmcv-1.4.6\mmcv\runner\epoch_based_runner.py", line 50, in train
    self.run_iter(data_batch, train_mode=True, **kwargs)
  File "h:\mmcv-1.4.6\mmcv\runner\epoch_based_runner.py", line 30, in run_iter
    **kwargs)
  File "h:\mmcv-1.4.6\mmcv\parallel\data_parallel.py", line 75, in train_step
    return self.module.train_step(*inputs[0], **kwargs[0])
  File "f:\2\underwater\excavating-roi-attention-for-underwater-object-detection-main\mmdet\models\detectors\base.py", line 248, in train_step
    losses = self(**data)
  File "D:\Anaconda3\envs\Excavating\lib\site-packages\torch\nn\modules\module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "h:\mmcv-1.4.6\mmcv\runner\fp16_utils.py", line 109, in new_func
    return old_func(*args, **kwargs)
  File "f:\2\underwater\excavating-roi-attention-for-underwater-object-detection-main\mmdet\models\detectors\base.py", line 172, in forward
    return self.forward_train(img, img_metas, **kwargs)
  File "f:\2\underwater\excavating-roi-attention-for-underwater-object-detection-main\mmdet\models\detectors\two_stage.py", line 150, in forward_train
    **kwargs)
  File "f:\2\underwater\excavating-roi-attention-for-underwater-object-detection-main\mmdet\models\roi_heads\standard_roi_head.py", line 106, in forward
_train
    img_metas)
  File "f:\2\underwater\excavating-roi-attention-for-underwater-object-detection-main\mmdet\models\roi_heads\standard_roi_head.py", line 135, in _bbox_f
orward_train
    bbox_results = self._bbox_forward(x, rois)
  File "f:\2\underwater\excavating-roi-attention-for-underwater-object-detection-main\mmdet\models\roi_heads\tr_head.py", line 63, in _bbox_forward
    bbox_cls_feats = bbox_cls_feats.view(b,num_sample,-1)
RuntimeError: shape '[4, 80, -1]' is invalid for input of size 4026624
`

` --------------------
2023-08-17 11:35:13,732 - mmdet - INFO - workflow: [('train', 1)], max: 12 epochs
2023-08-17 11:35:13,732 - mmdet - INFO - Checkpoints will be saved to F:\2\underwater\Excavating-RoI-Attention-for-Underwater-Object-Detection-main\work
_dirs\roitransformer_r50_fpn_1x_coco by HardDiskBackend.
2023-08-17 11:36:29,501 - mmdet - INFO - Epoch [1][50/1427]     lr: 4.945e-04, eta: 7:06:46, time: 1.500, data_time: 0.220, memory: 21211, loss_rpn_cls:
 0.6922, loss_rpn_bbox: 0.0198, loss_cls: 0.8305, acc: 90.4658, loss_bbox: 0.0731, loss: 1.6156
Traceback (most recent call last):
  File "tools/train.py", line 196, in <module>
    main()
  File "tools/train.py", line 192, in main
    meta=meta)
  File "f:\2\underwater\excavating-roi-attention-for-underwater-object-detection-main\mmdet\apis\train.py", line 209, in train_detector
    runner.run(data_loaders, cfg.workflow)
  File "h:\mmcv-1.4.6\mmcv\runner\epoch_based_runner.py", line 127, in run
    epoch_runner(data_loaders[i], **kwargs)
  File "h:\mmcv-1.4.6\mmcv\runner\epoch_based_runner.py", line 50, in train
    self.run_iter(data_batch, train_mode=True, **kwargs)
  File "h:\mmcv-1.4.6\mmcv\runner\epoch_based_runner.py", line 30, in run_iter
    **kwargs)
  File "h:\mmcv-1.4.6\mmcv\parallel\data_parallel.py", line 75, in train_step
    return self.module.train_step(*inputs[0], **kwargs[0])
  File "f:\2\underwater\excavating-roi-attention-for-underwater-object-detection-main\mmdet\models\detectors\base.py", line 248, in train_step
    losses = self(**data)
  File "D:\Anaconda3\envs\Excavating\lib\site-packages\torch\nn\modules\module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "h:\mmcv-1.4.6\mmcv\runner\fp16_utils.py", line 109, in new_func
    return old_func(*args, **kwargs)
  File "f:\2\underwater\excavating-roi-attention-for-underwater-object-detection-main\mmdet\models\detectors\base.py", line 172, in forward
    return self.forward_train(img, img_metas, **kwargs)
  File "f:\2\underwater\excavating-roi-attention-for-underwater-object-detection-main\mmdet\models\detectors\two_stage.py", line 150, in forward_train
    **kwargs)
  File "f:\2\underwater\excavating-roi-attention-for-underwater-object-detection-main\mmdet\models\roi_heads\standard_roi_head.py", line 106, in forward
_train
    img_metas)
  File "f:\2\underwater\excavating-roi-attention-for-underwater-object-detection-main\mmdet\models\roi_heads\standard_roi_head.py", line 135, in _bbox_f
orward_train
    bbox_results = self._bbox_forward(x, rois)
  File "f:\2\underwater\excavating-roi-attention-for-underwater-object-detection-main\mmdet\models\roi_heads\tr_head.py", line 68, in _bbox_forward
    bbox_cls_feats = self.roi_transformer(bbox_cls_feats)
  File "D:\Anaconda3\envs\Excavating\lib\site-packages\torch\nn\modules\module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "f:\2\underwater\excavating-roi-attention-for-underwater-object-detection-main\mmdet\models\roi_heads\tr_head.py", line 279, in forward
    bbox_feats = ea(bbox_feats)
  File "D:\Anaconda3\envs\Excavating\lib\site-packages\torch\nn\modules\module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "f:\2\underwater\excavating-roi-attention-for-underwater-object-detection-main\mmdet\models\roi_heads\tr_head.py", line 318, in forward
    attn = self.M_k(bbox_feats)
  File "D:\Anaconda3\envs\Excavating\lib\site-packages\torch\nn\modules\module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "D:\Anaconda3\envs\Excavating\lib\site-packages\torch\nn\modules\linear.py", line 93, in forward
    return F.linear(input, self.weight, self.bias)
  File "D:\Anaconda3\envs\Excavating\lib\site-packages\torch\nn\functional.py", line 1692, in linear
    output = input.matmul(weight.t())
RuntimeError: mat1 dim 1 must match mat2 dim 0
`
