### ISSUE TITLE
KeyError: 'TrHead is not in the models registry'

### ISSUE THREAD

**Issue by waqarmughal0002** [zsyasd/Excavating-RoI-Attention-for-Underwater-Object-Detection#4]
Try to ecuate the code but facing the issue mentioned. How can i sloved it?

2023-03-16 16:40:34,023 - mmdet - INFO - Set random seed to 1109083957, deterministic: False
/home/ubuntu/waqar/uw/uwo/lib/python3.9/site-packages/mmdet/models/builder.py:51: UserWarning: train_cfg and test_cfg is deprecated, please specify them in model
  warnings.warn(
/home/ubuntu/waqar/uw/uwo/lib/python3.9/site-packages/mmdet/models/detectors/two_stage.py:29: UserWarning: DeprecationWarning: pretrained is deprecated, please use "init_cfg" instead
  warnings.warn('DeprecationWarning: pretrained is deprecated, '
/home/ubuntu/waqar/uw/uwo/lib/python3.9/site-packages/mmdet/models/backbones/resnet.py:401: UserWarning: DeprecationWarning: pretrained is deprecated, please use "init_cfg" instead
  warnings.warn('DeprecationWarning: pretrained is deprecated, '
Traceback (most recent call last):
  File "/home/ubuntu/waqar/uw/uwo/lib/python3.9/site-packages/mmcv/utils/registry.py", line 69, in build_from_cfg
    return obj_cls(**args)
  File "/home/ubuntu/waqar/uw/uwo/lib/python3.9/site-packages/mmdet/models/detectors/faster_rcnn.py", line 19, in __init__
    super(FasterRCNN, self).__init__(
  File "/home/ubuntu/waqar/uw/uwo/lib/python3.9/site-packages/mmdet/models/detectors/two_stage.py", line 50, in __init__
    self.roi_head = build_head(roi_head)
  File "/home/ubuntu/waqar/uw/uwo/lib/python3.9/site-packages/mmdet/models/builder.py", line 40, in build_head
    return HEADS.build(cfg)
  File "/home/ubuntu/waqar/uw/uwo/lib/python3.9/site-packages/mmcv/utils/registry.py", line 237, in build
    return self.build_func(*args, **kwargs, registry=self)
  File "/home/ubuntu/waqar/uw/uwo/lib/python3.9/site-packages/mmcv/cnn/builder.py", line 27, in build_model_from_cfg
    return build_from_cfg(cfg, registry, default_args)
  File "/home/ubuntu/waqar/uw/uwo/lib/python3.9/site-packages/mmcv/utils/registry.py", line 61, in build_from_cfg
    raise KeyError(
**KeyError: 'TrHead is not in the models registry'**
During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ubuntu/waqar/uw/Excavating-RoI-Attention-for-Underwater-Object-Detection-main/tools/train.py", line 196, in <module>
    main()
  File "/home/ubuntu/waqar/uw/Excavating-RoI-Attention-for-Underwater-Object-Detection-main/tools/train.py", line 166, in main
    model = build_detector(
  File "/home/ubuntu/waqar/uw/uwo/lib/python3.9/site-packages/mmdet/models/builder.py", line 58, in build_detector
    return DETECTORS.build(
  File "/home/ubuntu/waqar/uw/uwo/lib/python3.9/site-packages/mmcv/utils/registry.py", line 237, in build
    return self.build_func(*args, **kwargs, registry=self)
  File "/home/ubuntu/waqar/uw/uwo/lib/python3.9/site-packages/mmcv/cnn/builder.py", line 27, in build_model_from_cfg
    return build_from_cfg(cfg, registry, default_args)
  File "/home/ubuntu/waqar/uw/uwo/lib/python3.9/site-packages/mmcv/utils/registry.py", line 72, in build_from_cfg
    raise type(e)(f'{obj_cls.__name__}: {e}')
**KeyError: "FasterRCNN: 'TrHead is not in the models registry'"**

**Comment by wwencc** [comment]
请问你解决这个问题了吗

**Comment by waqarmughal0002** [comment]
NO

**Comment by zsyasd** [comment]
please check whether your python version, mmedet version and pytorch version are consistent with mine. It looks like some conflicts caused by the wrong version.

**Comment by waqarmughal0002** [comment]
can you please share requirements.txt file from your running code. That
file contains all packages with versions.

**Comment by meixiangzhang** [comment]
After modifying the registry, run pip install - e. again. Maybe it can be solved.
